/* Listado inicial de inmuebles disponibles */ 
var PROPERTIES = [
    {
        description: 'Casa tradicional, completamente amueblada, naturaleza de vanguardia',
        address: 'calle Río Luna, 19',
        city: 'Besande',
        region: 'León',
        year:'1956',
        numberOfBedrooms: '5',
        price: '300.000',
        images: ['/images/leon1.jpg',
        '/images/leon2.jpg',
        '/images/leon3.jpg',
        '/images/leon4.jpg'],
        /* Añadir más propiedades según sean necesarias */
    },
    {
        /* Añadir aquí el segundo inmueble */
    
        description: 'En pleno corazón de los Picos de Europa, con vistas espectaculares al Naranco, ideal para desconectar y vivir apartado del mundo. El terreno incluye establo y granja.',
        address: 'calle Trasgo, s/n',
        city: 'Allende',
        region: 'Asturias',
        year:'1990 (reformada en el 2000)',
        numberOfBedrooms: '7',
        price: '550.000',
        images: ['/images/allende1.jpg',
        '/images/allende2.jpg',
        '/images/allende3.jpg',
        '/images/allende4.jpg',
        '/images/allende5.jpg',
        '/images/allende6.jpg'],
    },
    /* Añadir más inmuebles según sea necesario */
    {
        description: 'Chalet en paraje natural, vivienda tranquila a 1 km del pueblo',
        address: 'calle Rianxeira, 34',
        city: 'Saians',
        region: 'Pontevedra',
        year:'2013',
        numberOfBedrooms: '6',
        price: '355.000',
        images: ['/images/pontevedra1.jpg',
        '/images/pontevedra2.jpg',
        '/images/pontevedra3.jpg',
        '/images/pontevedra4.jpg'],
    },
    {
        description: 'Piso lujoso en el centro de Madrid, a 100 metros de transporte público, restaurantes y supermercados',
        address: 'Paseo de Recoletos, 21',
        city: 'Madrid',
        region: 'Madrid',
        year:'1945 (reformado recientemente)',
        numberOfBedrooms: '3',
        price: '1.000.000',
        images: ['/images/madrid1.jpg',
        '/images/madrid2.jpg',
        '/images/madrid3.jpg',
        '/images/madrid4.jpg',
        '/images/madrid9.jpg'],        
    },
    {
        description: 'Chalet a las afueras de Madrid, urbanización tranquila y situado en plena sierra de Somosierra',
        address: 'Avenida de Carlos III,24',
        city: 'Somosierra',
        region: 'Madrid',
        year:'2000',
        numberOfBedrooms: '6',
        price: '950.000',
        images: ['/images/madrid5.jpg',
        '/images/madrid6.jpg',
        '/images/madrid7.jpg'],        
    },
    {
        description: 'Chalet de lujo a las orillas del Mediterráneo, vistas al mar, vivienda vanguardista completamente amueblada',
        address: 'Carrer del Far,2',
        city: 'Begur',
        region: 'Gerona',
        year:'2015',
        numberOfBedrooms: '5',
        price: '5.000.000',
        images: ['/images/begur1.jpg',
        '/images/begur2.jpg',
        '/images/begur3.jpg',
        '/images/begur4.jpg',
        '/images/begur7.jpg'],        
    },
    {
        description: 'Chalet cerca del núcleo urbano, vistas al mar, a 1km de la playa',
        address: 'Carrer de la Tramontana,54',
        city: 'Begur',
        region: 'Gerona',
        year:'2001',
        numberOfBedrooms: '4',
        price: '900.000',
        images: ['/images/begurotra.jpg',
        '/images/begurotra2.jpg',
        '/images/begurotra3.jpg'],        
    },
     {
        description: 'Chalet en urbanización cercana al pueblo, amplio terreno para construir más edificios anexos',
        address: 'Calle carbayón, 43',
        city: 'Navia',
        region: 'Asturias',
        year:'1999',
        numberOfBedrooms: '5',
        price: '700.000',
        images: ['/images/navia1.jpg',
        '/images/navia2.jpg',
        '/images/navia3.jpg',
        '/images/navia4.jpg',
        '/images/navia6.jpg'],        
    },
    {
        description: 'Vivienda de lujo en pleno corazón del Parque Nacional de Banff, rodeado de naturaleza y cerca del núcleo urbano, ideal para los amantes del senderismo y los deportes de invierno',
        address: 'Carmilla Av.,4',
        city: 'Canmore',
        region: 'Alberta, Canada',
        year:'2014',
        numberOfBedrooms: '8',
        price: '5.900.000',
        images: ['/images/canmore1.jpg',
        '/images/canmore2.jpg',
        '/images/canmore4.jpg',
        '/images/canmore5.jpg',
        '/images/canmore7.jpg',
        '/images/canmore8.jpg'],        
    }
]